2023-07-25 20:20:36,408 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 20:20:36,410 - TeleBot - ERROR - Break infinity polling
2023-07-25 20:20:45,737 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. The server returned HTTP 431 Request Header Fields Too Large. Response body:
[b'']
2023-07-25 20:20:45,738 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pohofmd\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pohofmd\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pohofmd\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\apihelper.py", line 181, in _check_result
    result_json = result.json()
                  ^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 6770, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\tg_bots\tg-bot-ya-prac\app.py", line 100, in text_commands
    bot.send_photo(message.chat.id, file_1, file_2)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1825, in send_photo
    apihelper.send_photo(
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\apihelper.py", line 494, in send_photo
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\apihelper.py", line 184, in _check_result
    raise ApiHTTPException(method_name, result)
telebot.apihelper.ApiHTTPException: A request to the Telegram API was unsuccessful. The server returned HTTP 431 Request Header Fields Too Large. Response body:
[b'']

2023-07-25 20:21:08,139 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 20:21:08,140 - TeleBot - ERROR - Break infinity polling
2023-07-25 20:21:12,921 - TeleBot - ERROR - Infinity polling exception: '_io.BufferedReader' object has no attribute 'translate'
2023-07-25 20:21:12,922 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 6770, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\tg_bots\tg-bot-ya-prac\app.py", line 101, in text_commands
    bot.send_photo(message.chat.id, files)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1825, in send_photo
    apihelper.send_photo(
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\apihelper.py", line 494, in send_photo
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\apihelper.py", line 156, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\requests\models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\requests\models.py", line 556, in prepare_body
    (body, content_type) = self._encode_files(files, data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\requests\models.py", line 198, in _encode_files
    rf.make_multipart(content_type=ft)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\urllib3\fields.py", line 337, in make_multipart
    self._render_parts(
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\urllib3\fields.py", line 291, in _render_parts
    parts.append(self._render_part(name, value))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\urllib3\fields.py", line 262, in _render_part
    return self.header_formatter(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\urllib3\fields.py", line 113, in format_multipart_header_param
    value = value.translate({10: "%0A", 13: "%0D", 34: "%22"})
            ^^^^^^^^^^^^^^^
AttributeError: '_io.BufferedReader' object has no attribute 'translate'

2023-07-25 20:21:42,125 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 20:21:42,126 - TeleBot - ERROR - Break infinity polling
2023-07-25 20:21:44,811 - TeleBot - ERROR - Infinity polling exception: TeleBot.send_media_group() missing 1 required positional argument: 'media'
2023-07-25 20:21:44,812 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 6770, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\tg_bots\tg-bot-ya-prac\app.py", line 102, in text_commands
    bot.send_media_group(files)
TypeError: TeleBot.send_media_group() missing 1 required positional argument: 'media'

2023-07-25 20:22:11,019 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 20:22:11,020 - TeleBot - ERROR - Break infinity polling
2023-07-25 20:31:23,574 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 20:31:23,576 - TeleBot - ERROR - Break infinity polling
2023-07-25 20:31:38,815 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 20:31:38,815 - TeleBot - ERROR - Break infinity polling
2023-07-25 20:33:24,189 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 20:33:24,190 - TeleBot - ERROR - Break infinity polling
